### PR TITLE
models.BleachField's form field set to forms.BleachField

### LINKED ISSUE #13: Use forms.BleachField when models.BleachField is used
When defining a model field using `models.BleachField`, it won't automatically reflect on the ModelForm field.  Instead, the form field has to be defined separately using `forms.BleachField`.  I found this confusing initially given Django's "don't repeat yourself" style.

This can be solved by defining a `formfield` method in the `models.BleachField` class ([documentation](https://docs.djangoproject.com/en/2.2/howto/custom-model-fields/#specifying-form-field-for-model-field)).

Is there a reason why things are the way they are?  If you are you happy with this change, I will submit a pull request.

### PR DESCRIPTION
**Pull request by Alirezaja1384**
# Description

Describe: models.BleachField's form field automtically set to forms.BleachField in ModelForm

## References
Fix #13 

# Checklist

* [x] I have ran `tox` to ensure tests pass
* [ ] Usage documentation added in case of new features
* [x] Tests added / I have not lowered coverage from 100%

### CODE REVIEW

**Comment by marksweb** [comment]
@Alirezaja1384 This needs tests to ensure a model form uses the correct field.

Likely best done by updating the form tests to use the bleach form and a new `ModelForm` with a model in the test project.

**Comment by Alirezaja1384** [comment]
Ok, I'll do both soon.
Thanks for your review.

**Comment by Alirezaja1384** [comment]
I added another test for models.py and its coverage is now 100%. but I have no idea about forms.py. coverage report says line 35->37 are missed, but there are test_default_widget and test_custom_widget tests in test_settings.py.

**Comment by marksweb** [comment]
@Alirezaja1384 thank you.

I forget if its this package or another where the coverage from the github action isn't ran against all files in the app.

Essentially I need to find some time to look over things 😂👍

**Pull request merged**
