### PR TITLE
Added option to allow relative links

### PR DESCRIPTION
**Pull request by azaitsev**

### CODE REVIEW

**Comment by marksweb** [comment]
Could you please add some content to this PR to (at least) explain what it includes.

I have now added a [PR template](https://github.com/marksweb/django-bleach/blob/master/.github/pull_request_template.md) which might help you with what to include;

```
# Description

Describe:

* Content of the pull request
* Feature added / Problem fixed

## References

Provide any github issue fixed (as in ``Fix #XYZ``)

# Checklist

* [ ] I have ran `tox` to ensure tests pass
* [ ] Usage documentation added in case of new features
* [ ] Tests added / I have not lowered coverage from 100%
```

**Comment by marksweb** [comment]
@azaitsev it'd be good to get this merged. Can you take a look at the conflict please?

**Comment by Laityned** [comment]
allow_relative support is dropped by bleach in 2013 but there README is not up to date.

**Comment by marksweb** [comment]
Thanks @Laityned

In that case I'll close this.

**Pull request closed without merging**
