### PR TITLE
Mark saved data as safe

### LINKED ISSUE #35: Propose that the model field marks retrieved data as template safe
**Is your feature request related to a problem? Please describe.**
The problem here is similar to #27 in that when writing templates that render model instances with bleached data fields you need to explicitly mark each field as template safe. I think ad-hoc use of `mark_safe` is a bad practice and better practice would be to do it systematically.

I would have proposed this in #27 but at the time I was thinking that the model field already did this. I realised afterward that this is actually a local modification. Sorry for the spam!

**Describe the solution you'd like**
I would like the `BleachedField` model field to mark all data retrieved from the DB as template safe in `from_db_value()`.  The data is bleached before saving so anything read back is safe.

**Describe alternatives you've considered**
The default position is that the field doesn't mark anything safe and you need to mark bleached content as template safe every time it's used in a template.  This introduces an unnecessary human element in my view.

### PR DESCRIPTION
**Pull request by MrkGrgsn**
# Description

Marks bleach model field value as safe after the model is saved.

Fixes #35 but I went slightly further than the proposal and also marked the value safe in the in-memory object after it's saved.

I updated the README but not `/docs` - do you want those updated also?

# Checklist

* [X] I have ran `tox` to ensure tests pass
* [X] Usage documentation added in case of new features
* [X] Tests added / I have not lowered coverage from 100%

### CODE REVIEW

**Comment by marksweb** [comment]
@MrkGrgsn Thanks. If there is something appropriate that you could add to the docs, then that'd be great. Just because people might look there and not at the readme.

Also, could you add this extra field and test to the models tests to keep 100% coverage?

```
class BleachContent(models.Model):
    ...

    null_field = BleachField(blank=True, null=True)


class TestBleachModelField(TestCase):
    ...

    def test_saved_none_values_are_none(self):
        obj = BleachContent(null_field=None)
        obj.save()
        self.assertIsNone(obj.null_field)
```

**Review by marksweb — APPROVED** [review]

**Comment by marksweb** [comment]
Thanks @MrkGrgsn!

**Comment by MrkGrgsn** [comment]
No worries!  FYI, `/docs` and the README appear to be somewhat out-of-synch. There are some substantive differences plus formatting.

**Comment by marksweb** [comment]
@MrkGrgsn I've got no problem with different formatting, as long as the the information in each is accurate.

I prefer a README that's high level details - how you get started, any settings available to you.

Then the docs themselves can expand on that and go into details about what the package offers.

I did notice that there wasn't an actual link to the docs from the REAME though, so I've addressed that.

**Pull request merged**
